slack:
  token: xoxb-...
  channel: office
  message: ğŸ“¢ The office CO2 concentration has exceeded the safe threshold of 600ppm. Time to open the windows and let in some fresh air! ğŸƒ
datacake:
  key: ...
device: ...
threshold: 1
